name: macber_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0

  injectable: ^2.3.2
  get_it: ^7.6.4

  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  flutter_bloc: ^8.1.3





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.4.7

  injectable_generator: ^2.4.1

  json_serializable: ^6.7.1




flutter:
  uses-material-design: true
